hugoblox:
  theme:
    colors:
      primary: "#DA77AC"    # Your main pink
      secondary: "#F9B665"  # Your highlight orange
    surfaces:
      background: "#000000" # Black base
      foreground: "#FFFFFF" # White text
  typography:
    pack: academic
